name: Build
on:
  workflow_dispatch:
  push:
    paths-ignore:
      - .gitignore
      - "*.md"
  pull_request:
    paths-ignore:
      - .gitignore
      - "*.md"

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-24.04
            name: fitness_tracker-x86_64
          - os: ubuntu-24.04-arm
            name: fitness_tracker-arm64
  
    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version-file: ".python-version"

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libcairo2-dev \
            pkg-config \
            libgirepository-2.0-dev

      - name: Install dependencies
        run: uv sync --frozen --no-dev
        
      - name: Build
        run: uv build

      # Export deps to use for pex due to libpebble2 custom repo
      - name: Export Deps
        run: uv export --format requirements-txt --no-emit-project --no-dev --frozen --no-hashes -o dist/requirements.txt

      - name: Create PEX
        run: |
          uvx --python .venv/bin/python pex \
            -r dist/requirements.txt \
            dist/fitness_tracker-*.whl \
            -e fitness_tracker.main:main \
            -o dist/fitness_tracker.pex \
            --python-shebang '#!/usr/bin/env python3' \
            --scie eager \
            --scie-pbs-stripped

      - name: Upload Pex
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.name }}
          path: |
            dist/fitness_tracker
            dist/fitness_tracker.pex

      - name: Upload pex to GitHub Releases
        if: startsWith(github.ref, 'refs/tags/')
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.ref }}
          asset_name: ${{ matrix.name }}
          file: ${{ github.workspace }}/dist/fitness_tracker*
          file_glob: true

  package:
    needs: build
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-24.04
            package: deb
            name: fitness_tracker-x86_64
          - os: ubuntu-24.04-arm
            package: deb
            name: fitness_tracker-arm64
    steps:
      - uses: actions/checkout@v4

      - name: Download dist
        uses: actions/download-artifact@v4
        with:
          name: ${{ matrix.name }}
          path: dist

      - name: Fix permissions
        run: chmod +x dist/*

      - name: Setup ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ruby
          
      - name: Install fpm
        run: gem install fpm

      - name: Create deb package
        run: |
          VERSION=$(grep -E '^version\s*=' pyproject.toml | head -n1 | sed -E 's/version\s*=\s*"(.*)"/\1/')
          fpm -s dir -t ${{ matrix.package }} \
            -n fitness-tracker \
            -v "$VERSION" \
            dist/fitness_tracker=/usr/bin/fitness-tracker \
            dist/fitness_tracker.pex=/usr/bin/fitness-tracker.pex \
            data/fitness-tracker.desktop=/usr/share/applications/fitness-tracker.desktop \
            data/fitness-tracker.svg=/usr/share/icons/hicolor/scalable/apps/fitness-tracker.svg 

      - name: Upload Package
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.name }}.${{ matrix.package }}
          path: |
            *.${{ matrix.package }}

      - name: Upload packages to GitHub Releases
        if: startsWith(github.ref, 'refs/tags/')
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ${{ github.workspace }}/*.${{ matrix.package }}
          tag: ${{ github.ref }}
          file_glob: true

  pebble:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Install pebble-sdk
        run: |
          sudo apt update
          sudo apt install -y gcc-arm-none-eabi python3-pip python3-venv nodejs npm libsdl1.2debian libfdt1

          # pebble-tool always has a non-zero exit code even on success
          uv tool install pebble-tool || true
          pebble sdk install latest

      - name: Build Pebble app
        run: |
          cd pebble
          pebble build
          mkdir -p ../dist
          cp build/pebble.pbw ../dist/fitness_tracker.pbw

      - name: Upload Pebble app
        uses: actions/upload-artifact@v4
        with:
          name: fitness_tracker.pbw
          path: |
            dist/fitness_tracker.pbw
      
      - name: Upload Pebble app to GitHub Releases
        if: startsWith(github.ref, 'refs/tags/')
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ${{ github.workspace }}/dist/fitness_tracker.pbw
          asset_name: fitness_tracker.pbw
          tag: ${{ github.ref }}
